openshift_installer_dir: /data/openshift-installer
openshift_installer_version: latest
openshift_installer_source: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ openshift_installer_version }}/openshift-install-linux.tar.gz
openshift_installer_base_domain: example.com
openshift_installer_control_plane: []
openshift_installer_cluster_id: ocp
openshift_installer_cluster_cidr: 10.128.0.0/14
openshift_installer_service_cidr: 172.30.0.0/16
openshift_installer_fips_mode: False
openshift_installer_pull_secret: {}
openshift_installer_ssh_key: ''
openshift_installer_proxy: False
openshift_installer_proxy_http: ''
openshift_installer_proxy_https: ''
openshift_installer_proxy_noproxy: ''
openshift_installer_proxy_ca: ''
