#!/usr/bin/env ansible-playbook

- name: configure dhcp reservation
  blockinfile:
    path: /etc/dhcp/dhcpd.static.conf
    block: |
      host faros_{{ dhcp_name }} {
        hardware ethernet {{ dhcp_mac_address }};
        fixed-address {{ dhcp_ip }};
      }
    marker: "# {mark} MANAGED RECORD - {{ dhcp_name }}"
    create: yes
    owner: root
    group: root
    mode: 0640
    state: {% if dhcp_present|boolean %}present{% else %}absent{% endif %}
  notify: restart dhcpd
  delegate_to: dhcp
  become: yes
  when: not dhcp_ignore and not dhcp_absent

- name: configure dhcp ignoring
  blockinfile:
    path: /etc/dhcp/dhcpd.static.conf
    block: |
      host faros_ignore_{{ dhcp_name }} {
        hardware ethernet {{ dhcp_mac_address }};
        ignore booting;
      }
    marker: "# {mark} MANAGED RECORD - ignore_{{ dhcp_name }}"
    create: yes
    owner: root
    group: root
    mode: 0640
    state: {% if dhcp_present|boolean %}present{% else %}absent{% endif %}
  notify: restart dhcpd
  delegate_to: dhcp
  become: yes
  when: dhcp_ignore and not dhcp_absent

